
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const App = lazy(() => import("./pages/App.tsx"));
const ProductCatalog = lazy(() => import("./pages/ProductCatalog.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/product-catalog", element: <ProductCatalog />},
	{ path: "/productcatalog", element: <ProductCatalog />},

];
